# Generated by Django 3.0.6 on 2020-06-02 16:41

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(help_text='Категории оборудования', max_length=20, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.AddField(
            model_name='equipmentdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='equipment.EquipmentCategory'),
        ),
    ]
