# Generated by Django 3.0.6 on 2020-06-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200601_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='date',
        ),
    ]
