# Generated by Django 3.0.6 on 2020-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_postpage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(help_text='Категории постов', max_length=20, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категория поста',
            },
        ),
    ]
