# Generated by Django 3.0.6 on 2020-05-29 21:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0003_equipmentcarouselimages_equipmentdetailpage_equipmentlistpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcarouselimages',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='equipmentdetailpage',
            name='description',
            field=wagtail.core.fields.RichTextField(help_text='Общая информация', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipmentlistpage',
            name='subtitle',
            field=models.CharField(max_length=300, verbose_name='Коротко про оборудование'),
        ),
    ]
