# Generated by Django 3.0.6 on 2020-06-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0005_homepage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdetailpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='equipmentlistpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EquipmentCarouselImages',
        ),
        migrations.DeleteModel(
            name='EquipmentDetailPage',
        ),
        migrations.DeleteModel(
            name='EquipmentListPage',
        ),
    ]
