# Generated by Django 3.0.6 on 2020-05-28 20:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='Имя отчество', required=True)), ('last_name', wagtail.core.blocks.CharBlock(help_text='Фамилия', required=True)), ('position', wagtail.core.blocks.CharBlock(help_text='Ученое звание', required=True)), ('degree', wagtail.core.blocks.CharBlock(help_text='Ученая степень', required=False)), ('bio', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Био', required=False)), ('email', wagtail.core.blocks.EmailBlock(help_text='email', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(icon='user'))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
