# Generated by Django 3.0.6 on 2020-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200529_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetailpage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='persondetailpage',
            name='last_name',
        ),
    ]
