# Generated by Django 3.0.6 on 2020-05-29 10:13

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200529_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetailpage',
            name='education',
            field=models.CharField(blank=True, help_text='Образование', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persondetailpage',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Биография', null=True),
        ),
        migrations.AlterField(
            model_name='persondetailpage',
            name='degree',
            field=models.CharField(blank=True, help_text='Степень', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persondetailpage',
            name='position',
            field=models.CharField(blank=True, help_text='Позиция', max_length=50, null=True),
        ),
    ]
