# Generated by Django 3.0.6 on 2020-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200529_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetailpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
