# Generated by Django 3.0.6 on 2020-05-29 14:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_persondetailpage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetailpage',
            name='bio',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Общая информация', null=True),
        ),
    ]
